version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .
  pre_build:
    commands:
      - echo Running tests...
      - pytest tests/
  build:
    commands:
      - echo Packaging Lambda function...
      - zip -r function.zip src/
  post_build:
    commands:
      - echo Build completed. Uploading artifacts...

artifacts:
  files:
    - function.zip
  discard-paths: yes
