name: Deploy Lambda Functions

on:
  push:
    branches:
      - py-lambdas  # Trigger on push to main branch

jobs:
  deploy_lambda_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change this if needed
        
      - name: Current working directory
        run: ls -lah
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies for Lambda 1
        run: |
          cd aws-lambda-project/src/lambda_function_1
          pip install -r requirements.txt -t .
          zip -r ../lambda_function_1.zip *
      - name: Verify ZIP file exists
        run: ls -lah aws-lambda-project/src/

          
      - name: Deploy Lambda 1
        run: |
          aws lambda update-function-code \
          --function-name lambda_function_1 \
          --zip-file fileb://aws-lambda-project/src/lambda_function_1.zip \
          --region us-east-2 

          S3_BUCKET_NAME="python-lambda-pipeline-artifacts"
          LAMBDA_ZIP_DIRECTORY="aws-lambda-project/src/"

          # Upload Lambda zip file to S3
          if [ -f "$LAMBDA_ZIP_DIRECTORY/lambda_function_1.zip" ]; then
            aws s3 cp "$LAMBDA_ZIP_DIRECTORY/lambda_function_1.zip" s3://$S3_BUCKET_NAME/lambda_function_1.zip
            echo "Uploaded lambda_function_1.zip to s3://$S3_BUCKET_NAME/"
          else
            echo "No zip file found to upload."
          fi


  deploy_lambda_2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2  # Change this if needed
        
      - name: Install dependencies for Lambda 2
        run: |
          cd aws-lambda-project/src/lambda_function_2
          pip install -r requirements.txt -t .
          zip -r ../lambda_function_2.zip *
          
      - name: Deploy Lambda 2
        run: |
          aws lambda update-function-code \
          --function-name lambda_function_2 \
          --zip-file fileb://aws-lambda-project/src/lambda_function_2.zip \
          --region us-east-2 

          S3_BUCKET_NAME="python-lambda-pipeline-artifacts"
          LAMBDA_ZIP_DIRECTORY="aws-lambda-project/src/"

          # Upload Lambda zip file to S3
          if [ -f "$LAMBDA_ZIP_DIRECTORY/lambda_function_2.zip" ]; then
            aws s3 cp "$LAMBDA_ZIP_DIRECTORY/lambda_function_2.zip" s3://$S3_BUCKET_NAME/lambda_function_2.zip
            echo "Uploaded lambda_function_2.zip to s3://$S3_BUCKET_NAME/"
          else
            echo "No zip file found to upload."
          fi
          